// localhost

### getAllActors
GET http://localhost:8080/actors HTTP/1.1

### getActorById
GET http://localhost:8080/actors/667c895d4f0e4e74a12a8e11 HTTP/1.1

### getActorByName
GET http://localhost:8080/actors/name/liam%20neeson HTTP/1.1

### getActorByMovieTitle

### createActor
POST http://localhost:8080/actors HTTP/1.1
Content-Type: application/json

{
    "name": "Nicolas Cage",
    "gender": "Male",
    "dob": "1964-01-07",
    "dod": null,
    "nationality": "American"
}

### updateActor
PUT http://localhost:8080/actors/667ca158f9d47499c57b925e HTTP/1.1
Content-Type: application/json

{
    "name": "National Treasure",
    "gender": "Male",
    "dob": "1964-01-07",
    "dod": null,
    "nationality": "American"
}

### deleteActor
DELETE http://localhost:8080/actors/667dc6edccd7fb12549b1654 HTTP/1.1