### Get all reviews
GET http://localhost:8080/reviews

### Get a single review by review ID
GET http://localhost:8080/reviews/review/66803d088002b0e0de32ec4d

### Get reviews by user ID
GET http://localhost:8080/reviews/user/userId

### Get reviews by movie ID
GET http://localhost:8080/reviews/movie/movieId

### Create a new review
POST http://localhost:8080/reviews
Content-Type: application/json

{
    "user_id": "user_id_here",
    "movie_id": "movie_id_here",
    "rating": 5,
    "comment": "Great movie!"
}

### Update a review by review ID
PUT http://localhost:8080/reviews/update/66803d088002b0e0de32ec4d
Content-Type: application/json

{
    "rating": 4,
    "comment": "Liked it, but could have been better."
}

### Delete a review by review ID
DELETE http://localhost:8080/reviews/delete/66803d088002b0e0de32ec4d