// localhost

### getAllreviewss
GET http://localhost:8080/reviews

### getSinglereviews
GET http://localhost:8080/reviews/66803d088002b0e0de32ec4d

### getreviewsByTitle
GET http://localhost:8080/reviews/title/Star%20Wars:%20Attack%20of%20the%20Clones%20(Episode%20II)

### createreviews
POST http://localhost:8080/reviews
Content-Type: application/json

{
    "movie_id": "667b1de0f592b5c99c067fc6", 
    "rating": 4,
    "comment": "This movie was great!"
}

### updatereviews

PUT http://localhost:8080/reviews/66807a8ad26ffd2067994693
Content-Type: application/json

{
  "rating": 4,
  "comment": "This is an updated comment for the movie",
  "movie_id": "667b1de0f592b5c99c067fc6"
}


### deletereviews
DELETE http://localhost:8080/reviews/66807d076fbc7ebc80070f78

// render

### getAllreviewss
GET https://rate-a-reviews.onrender.com/reviews


### getSinglereviews
GET https://rate-a-reviews.onrender.com/reviews/66803d088002b0e0de32ec4d

### getreviewsByTitle
GET https://rate-a-reviews.onrender.com/reviews/title/Star%20Wars:%20Attack%20of%20the%20Clones%20(Episode%20II)

### createreviews
POST https://rate-a-reviews.onrender.com/reviews
Content-Type: application/json

{
    "movie_id": "667b1de0f592b5c99c067fc6", 
    "rating": 4,
    "comment": "This movie was great!"
}

### updatereviews

PUT https://rate-a-reviews.onrender.com/reviews/66807a8ad26ffd2067994693
Content-Type: application/json

{
  "rating": 4,
  "comment": "This is an updated comment for the movie",
  "movie_id": "667b1de0f592b5c99c067fc6"
}


### deletereviews
DELETE https://rate-a-reviews.onrender.com/reviews/66807d076fbc7ebc80070f78

